Publisher / Subscriber System, Testat Verteilte Systeme: Topic Class Reference
Topic Class Reference
Class for the Topic.
#include <topic.h>
Public Member Functions
Topic (string name)
Construct a new Topic object.
~Topic ()
Destroy the Topic object.
bool hasClient (string address, int port)
Evaluates whether the given subscriber is subscribed to this topic.
time_t getTimeoutTimestamp ()
Get the timeoutTimestamp value.
void setTimeoutTimestamp (time_t timestamp)
Set the timeoutTimestamp value.
void publishMessage ()
Send the message and messageTimestamp to all subscribers.
bool setMessage (string message)
Set the message value and update the messageTimestamp.
time_t getMessageTimestamp ()
Get the messageTimestamp value.
bool subscribe (ClientConnection *clientConnection)
Add a subscriber to the subscriberList.
bool unsubscribe (ClientConnection *clientConnection)
Remove a subscriber from the subscriberList.
string getTopicName ()
Get the Topic Name object.
vector< ClientConnection * > getClientConnections ()
Get the Client Connections List.
Private Attributes
string message
Stores the latest Message.
string topicName
Stores the name of the topic.
time_t messageTimestamp
vector< ClientConnection * > subscriberList
time_t timeoutTimestamp
Detailed Description
Class for the Topic.
Definition at line 15 of file topic.h.
Constructor & Destructor Documentation
Topic()
Topic::Topic (string name)
Construct a new Topic object.
Parameters
name Topic name
Definition at line 9 of file topic.cpp.
References message, messageTimestamp, and topicName.
~Topic()
Topic::~Topic ()
Destroy the Topic object.
Definition at line 19 of file topic.cpp.
References topicName.
Member Function Documentation
getClientConnections()
vector< ClientConnection * > Topic::getClientConnections ()
Get the Client Connections List.
Returns
vector<ClientConnection*> List of all ClientConnections
Definition at line 104 of file topic.cpp.
Referenced by Server::handleGetTopicStatus(), and Server::handleUnsubscribeRequest().
getMessageTimestamp()
time_t Topic::getMessageTimestamp ()
Get the messageTimestamp value.
Returns
time_t
Definition at line 69 of file topic.cpp.
References messageTimestamp.
Referenced by Server::handleGetTopicStatus().
getTimeoutTimestamp()
time_t Topic::getTimeoutTimestamp ()
Get the timeoutTimestamp value.
Returns
time_t Current timeout timestamp.
Definition at line 37 of file topic.cpp.
getTopicName()
string Topic::getTopicName ()
Get the Topic Name object.
Returns
string the Topic Name
Definition at line 99 of file topic.cpp.
References topicName.
hasClient()
bool Topic::hasClient (string address, int port)
Evaluates whether the given subscriber is subscribed to this topic.
Parameters
address IPv4 address of the subscriber.
port Port of the subscriber.
Returns
true if the subscriber is subscribed to this topic.
false if the subscriber is not subscribed to this topic.
Definition at line 24 of file topic.cpp.
publishMessage()
void Topic::publishMessage ()
Send the message and messageTimestamp to all subscribers.
Definition at line 47 of file topic.cpp.
References message, messageTimestamp, and topicName.
setMessage()
bool Topic::setMessage (string message)
Set the message value and update the messageTimestamp.
Parameters
message New message.
Definition at line 61 of file topic.cpp.
References message, and messageTimestamp.
Referenced by Server::handlePublishRequest().
setTimeoutTimestamp()
void Topic::setTimeoutTimestamp (time_t timestamp)
Set the timeoutTimestamp value.
Parameters
timestamp New timeout timestamp.
The timeout timestamp must be in the future.
Definition at line 42 of file topic.cpp.
subscribe()
bool Topic::subscribe (ClientConnection * clientConnection)
Add a subscriber to the subscriberList.
Parameters
clientConnection Pointer to the subscriber.
Returns
true if the subscriber was added.
false if the subscriber was not added.
Definition at line 74 of file topic.cpp.
References ClientConnection::getAddress(), and ClientConnection::getPort().
Referenced by Server::handleSubscribeRequest().
unsubscribe()
bool Topic::unsubscribe (ClientConnection * clientConnection)
Remove a subscriber from the subscriberList.
Parameters
clientConnection Pointer to the subscriber.
Returns
true if the subscriber was removed.
false if the subscriber was not removed.
Definition at line 85 of file topic.cpp.
References ClientConnection::getAddress(), and ClientConnection::getPort().
Referenced by Server::handleUnsubscribeRequest().
Member Data Documentation
message
string Topic::message private
Stores the latest Message.
Definition at line 114 of file topic.h.
messageTimestamp
time_t Topic::messageTimestamp private
Definition at line 121 of file topic.h.
subscriberList
vector<ClientConnection*> Topic::subscriberList private
Definition at line 122 of file topic.h.
timeoutTimestamp
time_t Topic::timeoutTimestamp private
Definition at line 123 of file topic.h.
topicName
string Topic::topicName private
Stores the name of the topic.
Definition at line 120 of file topic.h.
The documentation for this class was generated from the following files:
src/server/topic.h
src/server/topic.cpp