Publisher / Subscriber System, Testat Verteilte Systeme: Server Class Reference
Server Class Reference
Main Class for the Server.
#include <server.h>
Public Member Functions
Server (int port, int topicTimeout)
Construct a new Server object.
~Server ()
Destroy the Server object.
Private Member Functions
void startServer (int port)
Starts the server.
void checkTopicTimeouts ()
Checks for timed out topics and initiates send of last message, as well as resets the timeout.
void handleApproachingClient (int clientSocket, struct sockaddr_in *clientAddress)
Handles an approaching client.
Response handleSubscribeRequest (string ipAddress, int port, string topicName)
Handles a subscribe request. Creates a Topic if it does not exist. Returns a Success Status Code, if the user is subscribed.
Response handleUnsubscribeRequest (string ipAddress, int port, string topicName)
Handles a unsubscribe request. If the user is not longer subscribed to any topic, the clientConnection will be deleted. Returns a Failed Status Code, if the topic does not exist. Returns a Invalid Parameters Status Code, if the Topic does not exist. Returns a Success Status Code, if the topic exists and the user is unsubscribed.
Response handleListTopics ()
Handles a list topics request. Returns a Success Status Code and a list of all topics.
Response handleGetTopicStatus (string topicName)
Handles a get topic status request. Returns a Invalid Parameter Status Code, if the topic does not exist. Returns a Success Status Code and the topic status(MessageTimestamp, Subscriber[ip:port]), if the topic exists.
Response handlePublishRequest (string topicName, string message)
Handles a publish request. Returns a Invalid Parameter Status Code, if the topic does not exist. Returns a Success Status Code, if the topic exists and the message was published.
Private Attributes
mutex mtx
int port
int topicTimeout
vector< Topic * > topics
vector< ClientConnection * > clientConnections
thread timeoutCheckerThread
Detailed Description
Main Class for the Server.
Definition at line 18 of file server.h.
Constructor & Destructor Documentation
Server()
Server::Server (int port, int topicTimeout)
Construct a new Server object.
Parameters
topicTimeout Timeout in seconds.
port Port to listen on.
Creates and starts the timeoutCheckerThread thread. Logs the start of the server including the server address and port.
Definition at line 162 of file server.cpp.
References checkTopicTimeouts(), and topics.
~Server()
Server::~Server ()
Destroy the Server object.
Terminates the timeoutSendMessageCheckerThread thread. Removes all Topic and ClientConnection objects.
Definition at line 173 of file server.cpp.
Member Function Documentation
checkTopicTimeouts()
void Server::checkTopicTimeouts () private
Checks for timed out topics and initiates send of last message, as well as resets the timeout.
Definition at line 139 of file server.cpp.
References topics.
Referenced by Server().
handleApproachingClient()
void Server::handleApproachingClient (int clientSocket, struct sockaddr_in * clientAddress) private
Handles an approaching client.
Parameters
clientSocket client socket
clientAddress client address structure
Definition at line 19 of file server.cpp.
References BUFFER_SIZE, clientPort, Command::commandIdentifier, Command::deserialize(), Command::getCommandArgument(), getTopicStatus, internalError, listTopics, message, publish, Response::serialize(), Response::setStatusCode(), subscribe, topicName, and unsubscribe.
Referenced by startServer().
handleGetTopicStatus()
Response Server::handleGetTopicStatus (string topicName) private
Handles a get topic status request. Returns a Invalid Parameter Status Code, if the topic does not exist. Returns a Success Status Code and the topic status(MessageTimestamp, Subscriber[ip:port]), if the topic exists.
Parameters
topicName Topic to get the status from
Returns
Response
Definition at line 341 of file server.cpp.
References Topic::getClientConnections(), Topic::getMessageTimestamp(), getTopicStatus, internalError, invalidParameter, messageTimestamp, Response::setResponseArgument(), Response::setStatusCode(), subscribers, success, topicName, and topics.
handleListTopics()
Response Server::handleListTopics () private
Handles a list topics request. Returns a Success Status Code and a list of all topics.
Returns
Response
Definition at line 312 of file server.cpp.
References internalError, listTopics, Response::setResponseArgument(), Response::setStatusCode(), success, and topics.
handlePublishRequest()
Response Server::handlePublishRequest (string topicName, string message) private
Handles a publish request. Returns a Invalid Parameter Status Code, if the topic does not exist. Returns a Success Status Code, if the topic exists and the message was published.
Parameters
topicName Topic to publish to
message Message to publish
Returns
Response
Definition at line 398 of file server.cpp.
References failed, invalidParameter, message, publish, Topic::setMessage(), Response::setStatusCode(), success, topicName, and topics.
handleSubscribeRequest()
Response Server::handleSubscribeRequest (string ipAddress, int port, string topicName) private
Handles a subscribe request. Creates a Topic if it does not exist. Returns a Success Status Code, if the user is subscribed.
Parameters
ipAddress ip address of the client
port port of the client to receive Messages
topicName Topic to subscribe to
Returns
Response
Definition at line 179 of file server.cpp.
References failed, Response::setStatusCode(), Topic::subscribe(), subscribe, success, topicName, and topics.
handleUnsubscribeRequest()
Response Server::handleUnsubscribeRequest (string ipAddress, int port, string topicName) private
Handles a unsubscribe request. If the user is not longer subscribed to any topic, the clientConnection will be deleted. Returns a Failed Status Code, if the topic does not exist. Returns a Invalid Parameters Status Code, if the Topic does not exist. Returns a Success Status Code, if the topic exists and the user is unsubscribed.
Parameters
ipAddress ip address of the client
port port of the client to receive Messages
topicName Topic to unsubscribe from
Returns
Response
Definition at line 239 of file server.cpp.
References failed, ClientConnection::getAddress(), Topic::getClientConnections(), ClientConnection::getPort(), invalidParameter, Response::setStatusCode(), success, topicName, topics, Topic::unsubscribe(), and unsubscribe.
startServer()
void Server::startServer (int port) private
Starts the server.
Opens the Server Socket and handles approaching clients.
Parameters
port
Definition at line 94 of file server.cpp.
References handleApproachingClient().
Member Data Documentation
clientConnections
vector<ClientConnection*> Server::clientConnections private
Definition at line 45 of file server.h.
mtx
mutex Server::mtx private
Definition at line 41 of file server.h.
port
int Server::port private
Definition at line 42 of file server.h.
timeoutCheckerThread
thread Server::timeoutCheckerThread private
Definition at line 46 of file server.h.
topics
vector<Topic*> Server::topics private
Definition at line 44 of file server.h.
topicTimeout
int Server::topicTimeout private
Definition at line 43 of file server.h.
The documentation for this class was generated from the following files:
src/server/server.h
src/server/server.cpp