Publisher / Subscriber System, Testat Verteilte Systeme: Client Class Reference
Client Class Reference
Main Class for the Client.
#include <client.h>
Public Member Functions
Client (int port, string serverAddress, int serverPort)
Construct a new Client object.
~Client ()
Destroy the Client object.
void subscribeTopic (string topicName)
Subscribes to a topic.
void unsubscribe (string topicName)
Unsubscribes from a topic.
void publishTopic (string topicName, string message)
Publishes a message to a topic.
void listTopics ()
Lists all available topics.
void getTopicStatus (string topicName)
Retrieves the status of a topic.
void handleMessages ()
Handles incoming messages.
Private Member Functions
void sendMessage (Command &command)
Sends a given command to the server.
void logResponse (const Response &response, const string &senderIp, const string &senderPort)
Prints the information of a received response to the console.
void printMessage (Message message)
Prints a message to a topic with a timestamp to the console.
Private Attributes
int port
string serverAddress
int serverPort
int serverSocket
struct sockaddr_in serverAddr
int messageSocket
struct sockaddr_in clientAddr
atomic< bool > messageThreadRunning
thread messageThread
vector< string > subscribedTopics
Detailed Description
Main Class for the Client.
Definition at line 21 of file client.h.
Constructor & Destructor Documentation
Client()
Client::Client (int port, string serverAddress, int serverPort)
Construct a new Client object.
Parameters
port Set 0 for automatic port assignment
serverAddress IPv4 Address of the server
serverPort Port number of the server
Exceptions
runtime_error if the port is already in use
Starts a new thread (messageThread) that is listening for incoming messages on the defined port.
Definition at line 25 of file client.cpp.
References handleMessages().
~Client()
Client::~Client ()
Destroy the Client object.
Terminates the messageThread. Unsubscribes from all subscribed topics.
Definition at line 82 of file client.cpp.
References unsubscribe.
Member Function Documentation
getTopicStatus()
void Client::getTopicStatus (string topicName)
Retrieves the status of a topic.
Parameters
topicName The name of the topic to retrieve the status of.
Sends a getTopic request to the server. Receives the timestamp of the last message and prints it.
Definition at line 155 of file client.cpp.
References getTopicStatus, and topicName.
Referenced by main().
handleMessages()
void Client::handleMessages ()
Handles incoming messages.
This method runs on a separate thread and continuously listens for incoming messages from the server.
Definition at line 168 of file client.cpp.
References BUFFER_SIZE, Message::deserialize(), and message.
Referenced by Client().
listTopics()
void Client::listTopics ()
Lists all available topics.
Sends a list request to the server. Receives and prints a list of all available topics.
Definition at line 144 of file client.cpp.
References listTopics.
Referenced by main().
logResponse()
void Client::logResponse (const Response & response, const string & senderIp, const string & senderPort) private
Prints the information of a received response to the console.
Parameters
response Object containing the response information.
senderIp IP of the sender (server).
senderPort Port of the sender (server).
Definition at line 264 of file client.cpp.
References arrayStringToVectorString(), communicationParameterToStringDictionary, failed, Response::getAvailableArguments(), Response::getResponseArgument(), Response::getStatusCode(), internalError, invalidParameter, messageTimestamp, subscribers, success, and topics.
printMessage()
void Client::printMessage (Message message) private
Prints a message to a topic with a timestamp to the console.
Parameters
message The message object containing all informations.
Definition at line 197 of file client.cpp.
References message.
publishTopic()
void Client::publishTopic (string topicName, string message)
Publishes a message to a topic.
Parameters
topicName The name of the topic to publish the message to.
message The message to publish.
Sends a publish request to a specific topicName with an message
Definition at line 130 of file client.cpp.
References message, publish, and topicName.
Referenced by main().
sendMessage()
void Client::sendMessage (Command & command) private
Sends a given command to the server.
Parameters
command Object specifying the parameters to send.
Definition at line 205 of file client.cpp.
References BUFFER_SIZE, Command::commandIdentifier, Response::deserialize(), message, Command::serialize(), and SERVER_RESPONSE_TIMEOUT.
subscribeTopic()
void Client::subscribeTopic (string topicName)
Subscribes to a topic.
Parameters
topicName The name of the topic to subscribe to.
Sends a subscribe request to the server.
Definition at line 98 of file client.cpp.
References clientPort, subscribe, and topicName.
Referenced by main().
unsubscribe()
void Client::unsubscribe (string topicName)
Unsubscribes from a topic.
Parameters
topicName The name of the topic to unsubscribe from.
Sends a unsubscribe request to the server.
Definition at line 114 of file client.cpp.
References clientPort, topicName, and unsubscribe.
Member Data Documentation
clientAddr
struct sockaddr_in Client::clientAddr private
Definition at line 112 of file client.h.
messageSocket
int Client::messageSocket private
Definition at line 112 of file client.h.
messageThread
thread Client::messageThread private
Definition at line 116 of file client.h.
messageThreadRunning
atomic<bool> Client::messageThreadRunning private
Definition at line 115 of file client.h.
port
int Client::port private
Definition at line 107 of file client.h.
serverAddr
struct sockaddr_in Client::serverAddr private
Definition at line 110 of file client.h.
serverAddress
string Client::serverAddress private
Definition at line 108 of file client.h.
serverPort
int Client::serverPort private
Definition at line 109 of file client.h.
serverSocket
int Client::serverSocket private
Definition at line 110 of file client.h.
subscribedTopics
vector<string> Client::subscribedTopics private
Definition at line 117 of file client.h.
The documentation for this class was generated from the following files:
src/client/client.h
src/client/client.cpp