Publisher / Subscriber System, Testat Verteilte Systeme: Command Class Reference
Command Class Reference
Defines a class that represents a command that can be sent from the client to the server.
#include <command.h>
Public Member Functions
Command (CommandIdentifiers commandIdentifier)
Construct a new Command object using the specified command identifier.
Command ()
Construct a new Command object.
~Command ()
Destroy the Command object.
bool setCommandArgument (CommunicationParameters argumentName, string argumentValue)
Set the arguments for the command.
string getCommandArgument (CommunicationParameters argumentName) const
Get the Command Argument value.
bool isValid () const
Checks whether all required arguments are set.
string serialize () const
Serializes the command to a json string.
Static Public Member Functions
static Command deserialize (string serializedCommand)
Deserializes a json string to a command.
Public Attributes
CommandIdentifiers commandIdentifier
Specifies the command identifier.
Private Attributes
vector< CommunicationParameters > availableCommandArguments
Specifies the available command argument names.
vector< string > commandArguments
Specifies the command arguments.
Detailed Description
Defines a class that represents a command that can be sent from the client to the server.
Definition at line 15 of file command.h.
Constructor & Destructor Documentation
Command() [1/2]
Command::Command (CommandIdentifiers commandIdentifier)
Construct a new Command object using the specified command identifier.
Parameters
commandIdentifier The command identifier.
Definition at line 23 of file command.cpp.
References availableCommandArguments, commandArguments, commandDictionary, and commandIdentifier.
Command() [2/2]
Command::Command ()
Construct a new Command object.
Definition at line 19 of file command.cpp.
~Command()
Command::~Command ()
Destroy the Command object.
Definition at line 36 of file command.cpp.
Member Function Documentation
deserialize()
Command Command::deserialize (string serializedCommand) static
Deserializes a json string to a command.
Exceptions
runtime_error if the command cannot be deserialized or does not have all required values.
Parameters
serializedCommand The json-serialized command.
Returns
Command The deserialized command.
Definition at line 104 of file command.cpp.
References commandIdentifier, isValid(), setCommandArgument(), and stringToCommunicationParameterDictionary.
Referenced by Server::handleApproachingClient().
getCommandArgument()
string Command::getCommandArgument (CommunicationParameters argumentName) const
Get the Command Argument value.
Exceptions
runtime_error if the argument does not exist.
Parameters
argumentName The name of the argument.
Returns
string The value of the argument.
Definition at line 54 of file command.cpp.
References availableCommandArguments, commandArguments, and communicationParameterToStringDictionary.
Referenced by Server::handleApproachingClient().
isValid()
bool Command::isValid () const
Checks whether all required arguments are set.
Returns
true if the command is valid.
false if the command is invalid.
Definition at line 68 of file command.cpp.
References availableCommandArguments, commandArguments, and communicationParameterToStringDictionary.
Referenced by deserialize(), and serialize().
serialize()
string Command::serialize () const
Serializes the command to a json string.
Exceptions
runtime_error if the command cannot be serialized.
Returns
string The json-serialized command.
Definition at line 80 of file command.cpp.
References availableCommandArguments, commandArguments, commandIdentifier, communicationParameterToStringDictionary, and isValid().
Referenced by Client::sendMessage().
setCommandArgument()
bool Command::setCommandArgument (CommunicationParameters argumentName, string argumentValue)
Set the arguments for the command.
Parameters
argumentName The name of the argument.
argumentValue The new value of the argument.
Returns
true if the argument was set successfully.
false if the argument does not exist or cannot be set.
Definition at line 38 of file command.cpp.
References availableCommandArguments, commandArguments, and communicationParameterToStringDictionary.
Referenced by deserialize().
Member Data Documentation
availableCommandArguments
vector<CommunicationParameters> Command::availableCommandArguments private
Specifies the available command argument names.
Definition at line 84 of file command.h.
Referenced by Command(), getCommandArgument(), isValid(), serialize(), and setCommandArgument().
commandArguments
vector<string> Command::commandArguments private
Specifies the command arguments.
Definition at line 88 of file command.h.
Referenced by Command(), getCommandArgument(), isValid(), serialize(), and setCommandArgument().
commandIdentifier
CommandIdentifiers Command::commandIdentifier
Specifies the command identifier.
Definition at line 78 of file command.h.
Referenced by Command(), deserialize(), Server::handleApproachingClient(), Client::sendMessage(), and serialize().
The documentation for this class was generated from the following files:
src/shared/command.h
src/shared/command.cpp