Publisher / Subscriber System, Testat Verteilte Systeme: Response Class Reference
Response Class Reference
Defines a class that represents a server response to a client command.
#include <response.h>
Public Member Functions
Response (CommandIdentifiers commandIdentifier)
Construct a new Response object.
Response ()
Construct a new Response object.
~Response ()
Destroy the Response object.
bool setResponseArgument (CommunicationParameters argumentName, string argumentValue)
Set the Response Argument value if the argument exists.
bool setResponseArgument (CommunicationParameters argumentName, vector< string > argumentValue)
Set the Response Argument value to a vector of strings.
bool setResponseArgument (CommunicationParameters argumentName, uint64_t argumentValue)
Set the Response Argument value to a uint64_t.
string getResponseArgument (CommunicationParameters argumentName) const
Get the Response Argument value as string.
vector< CommunicationParameters > getAvailableArguments () const
Get a list of the available argument names.
bool setStatusCode (Statuscode statusCode)
Set the response status code.
Statuscode getStatusCode () const
Get the Status Code of the response.
string serialize () const
Serialize the response object to a JSON string.
Static Public Member Functions
static Response deserialize (CommandIdentifiers commandIdentifier, string serializedResponse)
Deserialize a JSON string to a response object.
Private Attributes
Statuscode statusCode
vector< CommunicationParameters > availableResponseArguments
vector< string > responseArguments
Detailed Description
Defines a class that represents a server response to a client command.
Definition at line 16 of file response.h.
Constructor & Destructor Documentation
Response() [1/2]
Response::Response (CommandIdentifiers commandIdentifier)
Construct a new Response object.
Parameters
commandIdentifier
Definition at line 14 of file response.cpp.
References availableResponseArguments, responseArguments, and responseDictionary.
Response() [2/2]
Response::Response ()
Construct a new Response object.
Definition at line 27 of file response.cpp.
~Response()
Response::~Response ()
Destroy the Response object.
Definition at line 29 of file response.cpp.
Member Function Documentation
deserialize()
Response Response::deserialize (CommandIdentifiers commandIdentifier, string serializedResponse) static
Deserialize a JSON string to a response object.
Exceptions
runtime_error if the JSON string is invalid (cannot be parsed).
Parameters
commandIdentifier Corresponding command identifier.
serializedResponse JSON serialized response.
Returns
Response
Definition at line 120 of file response.cpp.
References availableResponseArguments, communicationParameterToStringDictionary, setResponseArgument(), and setStatusCode().
Referenced by Client::sendMessage().
getAvailableArguments()
vector< CommunicationParameters > Response::getAvailableArguments () const
Get a list of the available argument names.
Returns
vector<string> List of available argument names.
Definition at line 87 of file response.cpp.
References availableResponseArguments.
Referenced by Client::logResponse().
getResponseArgument()
string Response::getResponseArgument (CommunicationParameters argumentName) const
Get the Response Argument value as string.
Exceptions
runtime_error if the argument does not exist.
Parameters
argumentName Name of the argument.
Returns
string Value of the argument.
Definition at line 71 of file response.cpp.
References availableResponseArguments, communicationParameterToStringDictionary, and responseArguments.
Referenced by Client::logResponse().
getStatusCode()
Statuscode Response::getStatusCode () const
Get the Status Code of the response.
Returns
Statuscode
Definition at line 98 of file response.cpp.
References statusCode.
Referenced by Client::logResponse().
serialize()
string Response::serialize () const
Serialize the response object to a JSON string.
Returns
string JSON string.
Definition at line 103 of file response.cpp.
References availableResponseArguments, communicationParameterToStringDictionary, responseArguments, and statusCode.
Referenced by Server::handleApproachingClient().
setResponseArgument() [1/3]
bool Response::setResponseArgument (CommunicationParameters argumentName, string argumentValue)
Set the Response Argument value if the argument exists.
Parameters
argumentName Name of the argument.
argumentValue Value of the argument.
Returns
true if the argument was set successfully.
false if the argument does not exist or cannot be set.
Definition at line 31 of file response.cpp.
References availableResponseArguments, communicationParameterToStringDictionary, and responseArguments.
Referenced by deserialize(), Server::handleGetTopicStatus(), Server::handleListTopics(), and setResponseArgument().
setResponseArgument() [2/3]
bool Response::setResponseArgument (CommunicationParameters argumentName, uint64_t argumentValue)
Set the Response Argument value to a uint64_t.
Parameters
argumentName Name of the argument.
argumentValue Value (uint64_t) of the argument.
Returns
true if the argument was set successfully.
false if the argument does not exist or cannot be set.
Definition at line 66 of file response.cpp.
References setResponseArgument().
setResponseArgument() [3/3]
bool Response::setResponseArgument (CommunicationParameters argumentName, vector< string > argumentValue)
Set the Response Argument value to a vector of strings.
Parameters
argumentName Name of the argument.
argumentValue Value (list of strings) of the argument.
Returns
true if the argument was set successfully.
false if the argument does not exist or cannot be set.
Definition at line 49 of file response.cpp.
References setResponseArgument().
setStatusCode()
bool Response::setStatusCode (Statuscode statusCode)
Set the response status code.
Parameters
statusCode
Returns
true if the status code was set successfully.
false if the status code cannot be set.
Definition at line 92 of file response.cpp.
References statusCode.
Referenced by deserialize(), Server::handleApproachingClient(), Server::handleGetTopicStatus(), Server::handleListTopics(), Server::handlePublishRequest(), Server::handleSubscribeRequest(), and Server::handleUnsubscribeRequest().
Member Data Documentation
availableResponseArguments
vector<CommunicationParameters> Response::availableResponseArguments private
Definition at line 117 of file response.h.
Referenced by deserialize(), getAvailableArguments(), getResponseArgument(), Response(), serialize(), and setResponseArgument().
responseArguments
vector<string> Response::responseArguments private
Definition at line 118 of file response.h.
Referenced by getResponseArgument(), Response(), serialize(), and setResponseArgument().
statusCode
Statuscode Response::statusCode private
Definition at line 116 of file response.h.
Referenced by getStatusCode(), serialize(), and setStatusCode().
The documentation for this class was generated from the following files:
src/shared/response.h
src/shared/response.cpp