Publisher / Subscriber System, Testat Verteilte Systeme: ClientConnection Class Reference
ClientConnection Class Reference
Class for the ClientConnection.
#include <clientconnection.h>
Public Member Functions
ClientConnection (string address, int port)
Construct a new Client Connection object.
~ClientConnection ()
Destroy the Client Connection object.
void SendMessage (string topicName, string message, time_t timestamp)
Sends a message to the client using the websocket.
string getAddress ()
Get the Address string.
int getPort ()
Get the Port number.
Private Attributes
string address
int port
Detailed Description
Class for the ClientConnection.
Definition at line 12 of file clientconnection.h.
Constructor & Destructor Documentation
ClientConnection()
ClientConnection::ClientConnection (string address, int port)
Construct a new Client Connection object.
Parameters
address IPv4 Address of the client
port Port of the client
Creates the Socket with the client.
Definition at line 13 of file clientconnection.cpp.
~ClientConnection()
ClientConnection::~ClientConnection ()
Destroy the Client Connection object.
Closes the socket.
Definition at line 20 of file clientconnection.cpp.
Member Function Documentation
getAddress()
string ClientConnection::getAddress ()
Get the Address string.
Returns
string IPv4 Address of the client
Definition at line 54 of file clientconnection.cpp.
Referenced by Server::handleUnsubscribeRequest(), Topic::subscribe(), and Topic::unsubscribe().
getPort()
int ClientConnection::getPort ()
Get the Port number.
Returns
int Port of the client
Definition at line 59 of file clientconnection.cpp.
Referenced by Server::handleUnsubscribeRequest(), Topic::subscribe(), and Topic::unsubscribe().
SendMessage()
void ClientConnection::SendMessage (string topicName, string message, time_t timestamp)
Sends a message to the client using the websocket.
Parameters
message Message to send
timestamp Timestamp of the message
The sent status code is always 0 (successful).
Definition at line 25 of file clientconnection.cpp.
References message, Message::serialize(), and topicName.
Member Data Documentation
address
string ClientConnection::address private
Definition at line 60 of file clientconnection.h.
port
int ClientConnection::port private
Definition at line 61 of file clientconnection.h.
The documentation for this class was generated from the following files:
src/server/clientconnection.h
src/server/clientconnection.cpp